apiVersion: apps/v1
kind: Deployment
metadata:
  name: ko-tester
spec:
  selector:
    matchLabels:
      app: ko-tester
  template:
    metadata:
      labels:
        app: ko-tester
    spec:
      containers:
      - name: ko-tester
        image: ko://github.com/izaakdale/ko-tester
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ko-tester
spec:
  selector:
    app: ko-tester
  ports:
  - port: 80
    targetPort: 80
