apiVersion: apps/v1
kind: Deployment
metadata:
  name: ko-tester
spec:
  selector:
    matchLabels:
      app: ko-tester
  template:
    metadata:
      labels:
        app: ko-tester
    spec:
      containers:
      - name: ko-tester
        image: ko://github.com/izaakdale/ko-tester
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ko-tester
spec:
  selector:
    app: ko-tester
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ko-tester
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: HostRegexp(`^(?:[^.]+\.)?izaakserver\.com$`) && PathPrefix(`/ko-tester`)
      services:
        - kind: Service
          name: ko-tester
          namespace: default
          port: 80
